"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var HttpCodes;
(function (HttpCodes) {
    // 1×× Informational
    HttpCodes.HTTP_CODE_CONTINUE = 100;
    HttpCodes.HTTP_CODE_SWITCHING_PROTOCOLS = 101;
    HttpCodes.HTTP_CODE_PROCESSING = 102;
    // 2×× Success
    HttpCodes.HTTP_CODE_OK = 200;
    HttpCodes.HTTP_CODE_CREATED = 201;
    HttpCodes.HTTP_CODE_ACCEPTED = 202;
    HttpCodes.HTTP_CODE_NON_AUTHORITATIVE_INFORMATION = 203;
    HttpCodes.HTTP_CODE_NO_CONTENT = 204;
    HttpCodes.HTTP_CODE_RESET_CONTENT = 205;
    HttpCodes.HTTP_CODE_PARTIAL_CONTENT = 206;
    HttpCodes.HTTP_CODE_MULTI_STATUS = 207;
    HttpCodes.HTTP_CODE_ALREADY_REPORTED = 208;
    HttpCodes.HTTP_CODE_IM_USED = 226;
    // 3×× Redirection
    HttpCodes.HTTP_CODE_MULTIPLE_CHOICES = 300;
    HttpCodes.HTTP_CODE_MOVED_PERMANENTLY = 301;
    HttpCodes.HTTP_CODE_FOUND = 302;
    HttpCodes.HTTP_CODE_SEE_OTHER = 303;
    HttpCodes.HTTP_CODE_NOT_MODIFIED = 304;
    HttpCodes.HTTP_CODE_USE_PROXY = 305;
    HttpCodes.HTTP_CODE_TEMPORARY_REDIRECT = 307;
    HttpCodes.HTTP_CODE_PERMANENT_REDIRECT = 308;
    // 4×× Client Error
    HttpCodes.HTTP_CODE_BAD_REQUEST = 400;
    HttpCodes.HTTP_CODE_UNAUTHORIZED = 401;
    HttpCodes.HTTP_CODE_PAYMENT_REQUIRED = 402;
    HttpCodes.HTTP_CODE_FORBIDDEN = 403;
    HttpCodes.HTTP_CODE_NOT_FOUND = 404;
    HttpCodes.HTTP_CODE_METHOD_NOT_ALLOWED = 405;
    HttpCodes.HTTP_CODE_NOT_ACCEPTABLE = 406;
    HttpCodes.HTTP_CODE_PROXY_AUTHENTICATION_REQUIRED = 407;
    HttpCodes.HTTP_CODE_REQUEST_TIMEOUT = 408;
    HttpCodes.HTTP_CODE_CONFLICT = 409;
    HttpCodes.HTTP_CODE_GONE = 410;
    HttpCodes.HTTP_CODE_LENGTH_REQUIRED = 411;
    HttpCodes.HTTP_CODE_PRECONDITION_FAILED = 412;
    HttpCodes.HTTP_CODE_PAYLOAD_TOO_LARGE = 413;
    HttpCodes.HTTP_CODE_REQUEST_URI_TOO_LONG = 414;
    HttpCodes.HTTP_CODE_UNSUPPORTED_MEDIA_TYPE = 415;
    HttpCodes.HTTP_CODE_REQUESTED_RANGE_NOT_SATISFIABLE = 416;
    HttpCodes.HTTP_CODE_EXPECTATION_FAILED = 417;
    HttpCodes.HTTP_CODE_I_M_A_TEAPOT = 418;
    HttpCodes.HTTP_CODE_MISDIRECTED_REQUEST = 421;
    HttpCodes.HTTP_CODE_UNPROCESSABLE_ENTITY = 422;
    HttpCodes.HTTP_CODE_LOCKED = 423;
    HttpCodes.HTTP_CODE_FAILED_DEPENDENCY = 424;
    HttpCodes.HTTP_CODE_UPGRADE_REQUIRED = 426;
    HttpCodes.HTTP_CODE_PRECONDITION_REQUIRED = 428;
    HttpCodes.HTTP_CODE_TOO_MANY_REQUESTS = 429;
    HttpCodes.HTTP_CODE_REQUEST_HEADER_FIELDS_TOO_LARGE = 431;
    HttpCodes.HTTP_CODE_CONNECTION_CLOSED_WITHOUT_RESPONSE = 444;
    HttpCodes.HTTP_CODE_UNAVAILABLE_FOR_LEGAL_REASONS = 451;
    HttpCodes.HTTP_CODE_CLIENT_CLOSED_REQUEST = 499;
    // 5×× Server Error
    HttpCodes.HTTP_CODE_INTERNAL_SERVER_ERROR = 500;
    HttpCodes.HTTP_CODE_NOT_IMPLEMENTED = 501;
    HttpCodes.HTTP_CODE_BAD_GATEWAY = 502;
    HttpCodes.HTTP_CODE_SERVICE_UNAVAILABLE = 503;
    HttpCodes.HTTP_CODE_GATEWAY_TIMEOUT = 504;
    HttpCodes.HTTP_CODE_HTTP_VERSION_NOT_SUPPORTED = 505;
    HttpCodes.HTTP_CODE_VARIANT_ALSO_NEGOTIATES = 506;
    HttpCodes.HTTP_CODE_INSUFFICIENT_STORAGE = 507;
    HttpCodes.HTTP_CODE_LOOP_DETECTED = 508;
    HttpCodes.HTTP_CODE_NOT_EXTENDED = 510;
    HttpCodes.HTTP_CODE_NETWORK_AUTHENTICATION_REQUIRED = 511;
    HttpCodes.HTTP_CODE_NETWORK_CONNECT_TIMEOUT_ERROR = 599;
})(HttpCodes = exports.HttpCodes || (exports.HttpCodes = {}));
//# sourceMappingURL=httpCodes.js.map