// 1×× Informational
export const HTTP_CODE_CONTINUE = 100;
export const HTTP_CODE_SWITCHING_PROTOCOLS = 101;
export const HTTP_CODE_PROCESSING = 102;

// 2×× Success
export const HTTP_CODE_OK = 200;
export const HTTP_CODE_CREATED = 201;
export const HTTP_CODE_ACCEPTED = 202;
export const HTTP_CODE_NON_AUTHORITATIVE_INFORMATION = 203;
export const HTTP_CODE_NO_CONTENT = 204;
export const HTTP_CODE_RESET_CONTENT = 205;
export const HTTP_CODE_PARTIAL_CONTENT = 206;
export const HTTP_CODE_MULTI_STATUS = 207;
export const HTTP_CODE_ALREADY_REPORTED = 208;
export const HTTP_CODE_IM_USED = 226;

// 3×× Redirection
export const HTTP_CODE_MULTIPLE_CHOICES = 300;
export const HTTP_CODE_MOVED_PERMANENTLY = 301;
export const HTTP_CODE_FOUND = 302;
export const HTTP_CODE_SEE_OTHER = 303;
export const HTTP_CODE_NOT_MODIFIED = 304;
export const HTTP_CODE_USE_PROXY = 305;
export const HTTP_CODE_TEMPORARY_REDIRECT = 307;
export const HTTP_CODE_PERMANENT_REDIRECT = 308;

// 4×× Client Error
export const HTTP_CODE_BAD_REQUEST = 400;
export const HTTP_CODE_UNAUTHORIZED = 401;
export const HTTP_CODE_PAYMENT_REQUIRED = 402;
export const HTTP_CODE_FORBIDDEN = 403;
export const HTTP_CODE_NOT_FOUND = 404;
export const HTTP_CODE_METHOD_NOT_ALLOWED = 405;
export const HTTP_CODE_NOT_ACCEPTABLE = 406;
export const HTTP_CODE_PROXY_AUTHENTICATION_REQUIRED = 407;
export const HTTP_CODE_REQUEST_TIMEOUT = 408;
export const HTTP_CODE_CONFLICT = 409;
export const HTTP_CODE_GONE = 410;
export const HTTP_CODE_LENGTH_REQUIRED = 411;
export const HTTP_CODE_PRECONDITION_FAILED = 412;
export const HTTP_CODE_PAYLOAD_TOO_LARGE = 413;
export const HTTP_CODE_REQUEST_URI_TOO_LONG = 414;
export const HTTP_CODE_UNSUPPORTED_MEDIA_TYPE = 415;
export const HTTP_CODE_REQUESTED_RANGE_NOT_SATISFIABLE = 416;
export const HTTP_CODE_EXPECTATION_FAILED = 417;
export const HTTP_CODE_I_M_A_TEAPOT = 418;
export const HTTP_CODE_MISDIRECTED_REQUEST = 421;
export const HTTP_CODE_UNPROCESSABLE_ENTITY = 422;
export const HTTP_CODE_LOCKED = 423;
export const HTTP_CODE_FAILED_DEPENDENCY = 424;
export const HTTP_CODE_UPGRADE_REQUIRED = 426;
export const HTTP_CODE_PRECONDITION_REQUIRED = 428;
export const HTTP_CODE_TOO_MANY_REQUESTS = 429;
export const HTTP_CODE_REQUEST_HEADER_FIELDS_TOO_LARGE = 431;
export const HTTP_CODE_CONNECTION_CLOSED_WITHOUT_RESPONSE = 444;
export const HTTP_CODE_UNAVAILABLE_FOR_LEGAL_REASONS = 451;
export const HTTP_CODE_CLIENT_CLOSED_REQUEST = 499;

// 5×× Server Error
export const HTTP_CODE_INTERNAL_SERVER_ERROR = 500;
export const HTTP_CODE_NOT_IMPLEMENTED = 501;
export const HTTP_CODE_BAD_GATEWAY = 502;
export const HTTP_CODE_SERVICE_UNAVAILABLE = 503;
export const HTTP_CODE_GATEWAY_TIMEOUT = 504;
export const HTTP_CODE_HTTP_VERSION_NOT_SUPPORTED = 505;
export const HTTP_CODE_VARIANT_ALSO_NEGOTIATES = 506;
export const HTTP_CODE_INSUFFICIENT_STORAGE = 507;
export const HTTP_CODE_LOOP_DETECTED = 508;
export const HTTP_CODE_NOT_EXTENDED = 510;
export const HTTP_CODE_NETWORK_AUTHENTICATION_REQUIRED = 511;
export const HTTP_CODE_NETWORK_CONNECT_TIMEOUT_ERROR = 599;
